# Build stage
FROM maven:3.8.6-openjdk-17 AS build

WORKDIR /app

# Copy the source code to the build container
COPY . .

# Build the application
RUN mvn clean package -DskipTests

# Runtime stage
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the built jar file from the build stage
COPY --from=build /app/target/spring-petclinic-*.jar /app/spring-petclinic.jar

# Download and install the JMX Prometheus Java agent
ADD https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar /jmx_prometheus_javaagent.jar

# Copy the Prometheus configuration file
COPY prometheus.yaml /config/prometheus.yaml

# Expose the necessary port for the application
EXPOSE 8080

# Set the entry point to run the Spring Boot application with the JMX Prometheus exporter
ENTRYPOINT ["java", "-javaagent:/jmx_prometheus_javaagent.jar=8080:/config/prometheus.yaml", "-jar", "/app/spring-petclinic.jar"]
